package com.bughunter.projecteular.qs1to10;
/****
 * QS2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
   By starting with 1 and 2, the first 10 terms will be:

			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	find the sum of the even-valued terms.
	Ans:4613732
 * 
 * 
 * @author lazysoftcoder
 * 
 */
public class QS2 {

	private static final long limitUnit = 1000000L;
	
	public static void main(String[]args) {
		long firstVal =1, secondVal =2;
		long sum=0,limit=4*limitUnit;
		
		while(secondVal<=limit) {
			
			sum += secondVal%2==0?secondVal:0;
			long nxtFiboNum = firstVal+secondVal;
			firstVal = secondVal;
			secondVal = nxtFiboNum;
		}
		System.out.println(sum);
	}
}
